# Generated by Django 4.2.9 on 2026-05-05 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Outfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('wear_type', models.CharField(choices=[('upper', 'Upper Wear'), ('lower', 'Lower Wear')], max_length=10)),
                ('occasions', models.CharField(max_length=200)),
                ('color', models.CharField(choices=[('white', 'White'), ('black', 'Black'), ('blue', 'Blue'), ('navy', 'Navy Blue'), ('red', 'Red'), ('pink', 'Pink'), ('green', 'Green'), ('gold', 'Gold / Yellow'), ('grey', 'Grey'), ('beige', 'Beige / Cream'), ('purple', 'Purple'), ('maroon', 'Maroon'), ('orange', 'Orange'), ('floral', 'Multi / Floral'), ('neutral', 'Neutral')], default='neutral', max_length=20)),
                ('style', models.CharField(choices=[('casual', 'Casual'), ('formal', 'Formal'), ('traditional', 'Traditional / Ethnic'), ('elegant', 'Elegant'), ('sports', 'Sports'), ('fusion', 'Fusion')], default='casual', max_length=20)),
                ('image', models.ImageField(upload_to='uploads/')),
                ('is_dummy', models.BooleanField(default=False)),
                ('dominant_rgb', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
